version: '3'

services:
  django:
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: redis-server --port 7777
  celery:
    build: ./news_app
    command: celery -A news_app worker -l info
    volumes:
      - ./news_app/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis

  celery-beat:
    build: ./news_app
    command: celery -A news_app beat -l info
    volumes:
      - ./news_app/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - celery
  db:
    image: postgres:13.9
    volumes:
      - /news_app:/var/lib/postgresql/data_app
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    