version: '3'

services:
  web:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    image: 'news_web'
    volumes:
      - ./news:/news

    ports:
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db
      
  redis:
    image: redis:alpine

    command: redis-server --port 7777
    ports:
      - "7777:7777"

  celery:
    restart: unless-stopped
    image: 'news_web'
    command: celery -A news_app worker -l info
    volumes:
      - /home/denis/Django-News-app/news_app/news/static:/news/static/
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - db

  celery-beat:
    restart: unless-stopped
    image: 'news_web'
    command: celery -A news_app beat -l info
    volumes:
      - /home/denis/Django-News-app/news_app/news/static:/news/static/
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - db
      - celery
    
  db:
    image: postgres:13.9
    volumes:
      - .:/var/lib/postgresql/data_app
    env_file:
      - ./.env
    ports:
      - "5432:5432"
