# Generated by Django 4.2 on 2023-04-19 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('poster_file_name', models.CharField(max_length=32, unique=True)),
                ('content', models.TextField()),
                ('source_link', models.CharField(default=None, max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32, unique=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.publication')),
            ],
        ),
    ]
