# Generated by Django 4.2 on 2023-04-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='introduction',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
