# Generated by Django 4.2 on 2023-04-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_publication_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='introduction',
            field=models.CharField(blank=True, default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
