# Generated by Django 4.2 on 2023-04-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_publication_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='time_created',
            field=models.DateTimeField(auto_created=True, default=None),
        ),
    ]
