# Generated by Django 4.2 on 2023-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_publication_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
