# Generated by Django 4.2 on 2023-04-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_publication_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-time_created']},
        ),
    ]
