# Generated by Django 4.2 on 2023-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_publication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='accepted_by_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='source_link',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
