# Generated by Django 4.2 on 2023-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_publication_accepted_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='source_link',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
