# Generated by Django 4.2 on 2023-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_publication_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='poster_file_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
