# Generated by Django 4.2 on 2023-04-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_publication_poster_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='accepted_by_admin',
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Reviewing', 'Reviewing')], default='Accepted', max_length=9),
        ),
    ]
