# Generated by Django 4.2 on 2023-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_publication_accepted_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Reviewing', 'Reviewing')], default='Accepted', max_length=9),
        ),
    ]
