# Generated by Django 4.2 on 2023-04-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_publication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_rejection', models.TextField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.publication')),
            ],
        ),
    ]
