# Generated by Django 4.2 on 2023-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_publication_news_public_title_2a8af3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
