# Generated by Django 4.2 on 2023-04-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_publication_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationfile',
            name='file_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
