# Generated by Django 4.2 on 2023-05-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_publicationfile_file_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publication',
            name='news_public_title_2a8af3_idx',
        ),
        migrations.RemoveIndex(
            model_name='rejectedpublication',
            name='news_reject_publica_43309f_idx',
        ),
    ]
